stages:
  - build
  - deploy

variables:
  TAG: $CI_PIPELINE_ID
  FILES_PATH: /mnt/build-images/k8s/service-provider

build:
  stage: build
  environment: development
  only:
  - master
  tags:
  - credibank
  - docker image
  script:
  - $FILES_PATH/build-image.sh

deploy:
  stage: deploy
  environment: development
  only:
  - master
  when: manual
  tags:
  - credibank
  - docker image
  script:
  - $FILES_PATH/deploy-image.sh
